### ISSUE TITLE
A question about unitypackage

### ISSUE THREAD

**Issue by Rokudo03** [yoship1639/UniToon#4]
Excuse me first,
I tryed Unitoon shader (V.alpha) but when I apply it the material turn transparent. 
As I had somme errors in the log I wonder that it may come from the preloads settings of my project.
So if you please, do you have any list of the preloaded unitypackage (version) you use in the project ( like Univrm I guessed ).
That way I can recreate the same conditions.
Thank you for your attention, and have a nice day.

**Comment by yoship1639** [comment]
Thank you for your question.
Unitoon is currently the only shader package that supports only URP, so the only package it depends on is the URP package. Therefore, no other packages are required. 
Also, UniToon includes a different version than the Unity version you are currently using, so older (or newer) versions of UniToon will output an error because they are not compatible, but they will still work.
Please check the following.

* Do you have the URP package installed?
* Are you configured to use URP?
* Do you have the latest UniToon package installed?
* Is the version of UniToon appropriate? ex) Unity2021.2.12f1 -> URP_2021_2

**Comment by Rokudo03** [comment]
Thank you much for your quick response.
I did a tabula rasa and restarted a new URP project with the correct version just as you said, and now it worked.
Well actually it almost worked, because now I don't know how to export my character as a proper VRM.
I tryed it didn't worked ( with Univrm ) or did I do it wrong...
Thank you for your help, and have a nice day too.
